NugetSample/Models/Particular/Particular.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using IdentitySample.Models;

namespace IdentitySample.Models
{
    [Table("Particulares")]
    public class Particular
    {
        [Key]
        public int ParticularId { get; set; }

        [Column("Nome" )]
        public string Nome { get; set; }

        [Column("Identificacao")]
        public int Bi { get; set; }

        [Column("Morada")]
        public string Morada { get; set; }
        
        [Column("DatadeNascimento")]
        public DateTime DataNascimento { get; set; }

        [Column("CartadeConducao")]
        public string Cconducao { get; set; }

        [Column("Email")]
        public string Email { get; set; }

        [Column("Telefone")]
        public int Tel { get; set; }


        //tem avaliação como cliente(conjunto de criticas de cliente)
        public IList<Critcliente> Classificacli { get; set; }
        
        //tem avaliação como fornecedor(conjunto de criticas de fornecedor)
        public IList<CritFornecedor> Classificaforn { get; set; }
        
        //tem um ou mais carros para alugar
        public IList<Carro> Carros { get; set; }

        //pode alugar carros
        public IList<Carro> Carroalugados { get; set; }

        //presta serviços
        public IList<Servicos> Servicoses { get; set; }

        //tem uma ou mais zonas de atuacao
        public IList<Zonas> Zonases { get; set; }

        //adicionar aqui uma lista de mensagens?
        public IList<Mensagem> Mensagens { get; set; }

        public Particular()
        {

        }
    }//fim da classe Particular
}

NugetSample/Models/Particular/ViewModelParticular.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IdentitySample.Models
{
    public class ViewModelParticular
    {
        [Required(ErrorMessage = "O nome é campo obrigatório!")]
        [Display(Name = "Nome: ")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O campo Identificação obrigatório!")]
        [Display(Name = "Identificação(BI): ")]
        [RegularExpression(@"^\d{8}$", ErrorMessage = "O BI tem de conter 8 algarismos!")]
        public int Bi { get; set; }

        [Required(ErrorMessage = "O campo Morada obrigatório!")]
        [Display(Name = "Morada: ")]
        public string Morada { get; set; }

        [Display(Name = "Data de Nascimento: ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        //falta custom validator
        public DateTime DataNascimento { get; set; }

        [Required(ErrorMessage = "O campo Carta de Condução é obrigatório")]
        [Display(Name = "Carta de Condução: ")]
        [RegularExpression(@"^[A-Z] - \d{6} \d{1}$",ErrorMessage = "Insira o seu numero da carta de condução no formato Letra(Maiúscula) - (6 algarismos) (1 algarismo)!")]
        public string Cconducao { get; set; }

        

        [Required]
        [Display(Name = "Email: ")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required(ErrorMessage = "Insira o seu contacto!")]
        [Display(Name = "Contacto: ")]
        [DataType(DataType.PhoneNumber)]
        public int Tel { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [StringLength(100, ErrorMessage = "A {0} deve ter pelo menos {2} caracters.", MinimumLength = 5)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar password")]
        [Compare("Password", ErrorMessage = "As passwords não coincidem")]
        public string ConfirmPassword { get; set; }


    }
}

NugetSample/Controllers/ParticularsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;

namespace IdentitySample.Controllers
{
    [Authorize(Roles ="Admin,Particular")]
    public class ParticularsController : Controller
    {
        private ApplicationDbContext db;
        protected ApplicationDbContext ApplicationDbContext { get; set; }
        protected UserManager<ApplicationUser> UserManager { get; set; }

        public ParticularsController()
        {
            db = new ApplicationDbContext();
            this.ApplicationDbContext = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));
        }

        // GET: Particulars
        public ActionResult Index()
        {
            return View(db.Particulares.ToList());
        }

        // GET: Particulars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Particular particular = db.Particulares.Find(id);
            if (particular == null)
            {
                return HttpNotFound();
            }
            return View(particular);
        }

        // GET: Particulars/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Particulars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ViewModelParticular model)
        {
            if (ModelState.IsValid)
            {
                var dados = new Particular
                {
                    Nome = model.Nome,
                    Bi = model.Bi,
                    Morada = model.Morada,
                    DataNascimento = model.DataNascimento,
                    Cconducao = model.Cconducao,
                    Email = model.Cconducao,
                    Tel = model.Tel
                };

                db.Particulares.Add(dados);
                db.SaveChanges();

                var user = new ApplicationUser
                {
                    UserName = model.Email,
                    Email = model.Email,
                    Perfil = "Particular",
                    ParticularId = dados.ParticularId
                };

                var adminresult = await UserManager.CreateAsync(user, model.Password);
                //Add User ao Role
                if (adminresult.Succeeded)
                {
                    var result = await UserManager.AddToRoleAsync(user.Id, "Particular");
                    if (!result.Succeeded)
                    {
                        ModelState.AddModelError("",result.Errors.First());
                        return View();
                    }
                 
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    return View();
                }

                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: Particulars/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Particular particular = db.Particulares.Find(id);
            if (particular == null)
            {
                return HttpNotFound();
            }
            return View(particular);
        }

        // POST: Particulars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ParticularId,Nome,Bi,Morada,DataNascimento,Cconducao,Email,Tel")] Particular particular)
        {
            if (ModelState.IsValid)
            {
                db.Entry(particular).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(particular);
        }

        // GET: Particulars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Particular particular = db.Particulares.Find(id);
            if (particular == null)
            {
                return HttpNotFound();
            }
            return View(particular);
        }

        // POST: Particulars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Particular particular = db.Particulares.Find(id);
            db.Particulares.Remove(particular);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NugetSample/Views/Particulars/Create.cshtml
@model IdentitySample.Models.ViewModelParticular

@{
    ViewBag.Title = "Novo Particular";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Create","Particulars",FormMethod.Post,new{@class="form-horizontal",role ="form"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Criar Novo Particular</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Morada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Morada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Morada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cconducao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cconducao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cconducao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tel, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NugetSample/Views/Particulars/Delete.cshtml
@model IdentitySample.Models.Particular

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Particular</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Morada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Morada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cconducao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cconducao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tel)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NugetSample/Views/Particulars/Details.cshtml
@model IdentitySample.Models.Particular

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Particular</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Morada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Morada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cconducao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cconducao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tel)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ParticularId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NugetSample/Views/Particulars/Edit.cshtml
@model IdentitySample.Models.Particular

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Particular</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ParticularId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Morada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Morada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Morada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cconducao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cconducao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cconducao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NugetSample/Views/Particulars/Index.cshtml
@model IEnumerable<IdentitySample.Models.Particular>

@{
    ViewBag.Title = "Particulares";
}

<h2>Particulares</h2>

<p>
    @Html.ActionLink("Novo Particular", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Morada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cconducao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tel)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Morada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataNascimento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cconducao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tel)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ParticularId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ParticularId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ParticularId })
        </td>
    </tr>
}

</table>